dist: bionic

addons:
  chrome: stable

language: python

cache: pip

python:
  - 3.6
  - 3.7
  - 3.8

services:
  - docker

before_install:
  # Install testing dependencies
  - pip install black coveralls flake8 pytest pytest-cov

script:
  # Stop build if python files arent formatted correctly
  - black --check --verbose .
  # Stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  # Run unit tests
  - pytest --verbose

after_success:
  - coveralls

notifications:
  on_success: change
  on_failure: change
